export default [
  'Wealth is attracted to me',
  'i will succeed',
  'success is a virtue',
  'my life has value',
  'success is right around the corner',
  `i am worthy of being wealthy`,
  `i am a magnet for money`,
  `i am a magnet for financial prosperity`,
  `prosperity is drawn to me`,
  `money comes to me in expected and unexpected ways`,
  `i am worthy of making more money`,
  `i am receptive to all avenues of wealth`,
  `i embrace new sources of income`,
  `i welcome all forms of income and wealth into my life`,
  `i release all negative energy about money`,
  `money comes to me easily and effortlessly`,
  `money flows to me effortlessly`,
  `wealth constantly flows into my life`,
  `my actions create prosperity`,
  `i am aligned with the energy of abundance`,
  `i constantly attract opportunities that create more money`,
  `my finances are improving beyond my dreams`,
  `money is the root of joy and comfort`,
  `money and spirituality coexist in harmony`,
  `i am the master of my wealth`,
  `i am able to handle large sums of money`,
  `i am worthy of a wealthy life`,
  `i am a vessel for abundance to flow through`,
  `i am a financial genius`,
  `i am living an abundant and fulfilling life`,
  `i am open to limetless opportunities for wealth`,
  `i am constantly expanding my financial horizons`,
  `i am a conduit for wealth and success`,
  `i am attracting lucrative opportunities`,
  `I am a wealth builder`,
  `My fortune grows daily`,
  `I am financially blessed`,
  `I am a magnet for positive financial outcomes`,
  `I am worth of all the financial abundance in the universe`,
  `i am rich in mind, body, and spirit`,
  `i am a master for manifesting wealth`,
  `i am the creater of my financial destiny`,
  `i am open to infinite wealth`,
  `i am fnancially free and secure`,
  `i am open to multiple streams of income`,
  `i am a money making machine`,
  `i am always in the right place at the right time for financial success`,
  `i accept all the joy and prosperity the universe has to offer`,
  `financial success comes to me easily and effortlessly`,
  `my income exceeds my expenses`,
  `every day my mind moves towards wealth`,
  `i am financially free`,
  `i am a money magnet`,
  `wealth and abundance flow to me`,
  `i am open to receiving money`,
  `i attract money  easily and effortlessly`,
  `i deserve financial success`,
  `i am an excellent mony manager`,
  `My Soul is destined for limitless prosperity.`,
  `The Universe provides me with infinite Abundance.`,
  `I dissolve all scarcity programs imprinted in my DNA.`,
  `I am free from generational patterns of lack.`,
  `The Universe restores my financial sovereignty.`,
  `I am worthy of receiving limitless wealth.`,
  `I clear all energetic debts carried from past generations.`,
  `I accept and welcome infinite streams of income.`,
  `My Energy Field radiates the vibration of Abundance.`,
  `The Universe supports my highest financial potential.`,
  `I clear all past-life money karma and step into new Abundance.`,
  `My financial reality is Divinely transformed and uplifted.`,
  `I am empowered to create limitless financial opportunities.`,
  `I release all ancestral poverty patterns from my lineage.`,
  `I break free from all inherited financial limitations.`,
  `Wealth flows to me effortlessly, guided by the Universe.`,
  `I am Divinely supported in my journey to financial freedom.`,
  `My ancestral wounds around money are healed and transmuted.`,
  `The wealth of my ancestors flows through me in Divine Abundance.`,
  `My Soul recognizes and claims its Infinite Prosperity.`,
  `The Universe reprograms my Energy Field for financial success.`,
  `I step fully into my Divine inheritance of Abundance.`,
  `I release fear and guilt around money, past and present.`,
  `My financial destiny is rewritten in Divine Prosperity.`,
  `The Universe aligns me with effortless wealth.`,
  `I transmute ancestral money wounds into golden opportunities.`,
  `My Soul is liberated from all financial burdens.`,
  `I dissolve all subconscious resistance to Abundance.`,
  `Money is my Divine birthright, and I claim it now.`,
  `The Universe clears all obstacles to my financial expansion.`,
  `I embrace new, prosperous money beliefs with joy.`,
  `The joy of Abundance is deeply rooted in my subconscious.`,
  `I open my heart and mind to unlimited financial blessings.`,
  `I honor my ancestors by creating a legacy of wealth.`,
  `Every step I take brings me closer to financial empowerment.`,
  `I am always Divinely provided for by the Universe.`,
  `My Soul vibrates in perfect alignment with wealth.`,
  `I now release all fears of financial success.`,
  `The Universe replaces all scarcity with Divine Abundance.`,
  `I remove all hidden money blocks with ease and grace.`,
  `My ancestral lineage is now cleansed of financial struggles.`,
  `I am no longer bound by limiting beliefs about money.`,
  `My Soul expands into Divine financial sovereignty.`,
  `I step into a new timeline of prosperity and ease.`,
  `The Universe rewards my willingness to receive Abundance.`,
  `I trust in my Divine ability to generate wealth effortlessly.`,
  `I allow financial miracles to unfold in my life.`,
  `I break every ancestral vow of poverty with love and grace.`,
  `The Universe pours unlimited financial blessings upon me.`,
  `I attract wealth, prosperity, and success with ease.`,
  `The Souls of my ancestors celebrate my financial freedom.`,
  `I am grateful for the Divine wealth flowing into my life.`,
  `The Universe blesses my path with golden opportunities.`,
  `I release all fear of financial expansion and welcome success.`,
  `I activate the codes of wealth deep within my Soul.`,
  `I dissolve all lack-based programming in my subconscious.`,
  `I am a Divine magnet for prosperity in all forms.`,
  `The Universe realigns me with my highest financial destiny.`,
  `I transmute all ancestral financial wounds into wealth.`,
  `My Soul recognizes the endless abundance available to me.`,
  `I trust the Universe to guide me to financial success.`,
  `I receive wealth in perfect alignment with my highest good.`,
  `My ancestors celebrate the wealth I now manifest.`,
  `I honor my lineage by embracing prosperity fully.`,
  `My Soul is infinitely abundant, always and forever.`,
  `I am free to experience money as a sacred energy of expansion.`,
  `The Universe multiplies my wealth in miraculous ways.`,
  `I am ready to claim the wealth that has always been mine.`,
  `I AM ABOUT TO WALK INTO THE MOST ABUNDANT BALANCED WEALTHY AND SUCCESSFUL PERIOD OF MY LIFE.`,
  `I NATURALLY ATTRACT GOOD FORTUNE`,
  `I AM WEALTHY IN MORE WAYS THAN ONE.`,
  `I GIVE MYSELF PERMISSION TO PROSPER`,
  `I HAVE THE POWER TO BUILD THE LIFE THAT I DESIRE.`,
  `I am energetically aligned with unlimited abundance.`,
  `I am worthy of financial freedom and security.`,
  `My subconscious mind welcomes prosperity with open arms.`,
  `Money is an extension of my natural energy flow.`,
  `Every dollar I receive expands my financial abundance.`,
  `I am open to new streams of income.`,
  `My vibration is magnetized to wealth.`,
  `Money flows to me like a river of endless abundance.`,
  `I trust that financial prosperity is my birthright.`,
  `I deserve wealth, and I accept it now.`,
  `I am a magnet for high-vibrational wealth.`,
  `I release all resistance to financial prosperity.`,
  `Money flows to me in miraculous ways.`,
  `Wealth flows to me effortlessly and abundantly.`,
  `I dissolve all fear and doubt about receiving wealth.`,
  `Prosperity comes to me in expected and unexpected ways.`,
  `I trust the Universe to provide for me abundantly.`,
  `My thoughts and beliefs support unlimited wealth.`,
  `I attract financial blessings with ease.`,
  `I allow myself to receive wealth effortlessly.`,
  `I am divinely supported in all my financial endeavors.`,
  `The more I relax, the more money flows to me.`,
  `I am grateful for the financial blessings in my life.`,
  `Every day, my wealth expands in miraculous ways.`,
  `I effortlessly manifest financial abundance.`,
  `The energy of prosperity surrounds and fills me.`,
  `I am a natural receiver of wealth.`,
  `The Universe always provides me with more than enough.`,
  `My subconscious mind is programmed for financial success.`,
  `I dissolve all limiting beliefs about money.`,
  `The more I give, the more I receive.`,
  `Opportunities for financial growth are everywhere.`,
  `My bank account grows effortlessly.`,
  `I am free from all financial worries.`,
  `Money loves me and finds its way to me easily.`,
  `I trust the Divine flow of abundance in my life.`,
  `My financial situation improves every day.`,
  `I radiate prosperity, and it returns to me multiplied.`,
  `Money is a tool for my happiness and success.`,
  `I receive financial blessings from known and unknown sources.`,
  `The energy of money is always flowing toward me.`,
  `I am financially free and independent.`,
  `I am aligned with infinite prosperity.`,
  `My income is constantly increasing.`,
  `I release all guilt and fear around wealth.`,
  `I am in a constant state of gratitude for my abundance.`,
  `My subconscious fully supports my financial success.`,
  `I trust that money comes to me with ease.`,
  `I am always in the right place at the right time for financial success.`,
  `Abundance is my natural state, and I fully embrace it now.`,
  `my financial blessings are numerous and bountiful`,
]



export const mantras = [
  'MONEY VORTEX',
  'ABUNDANCE GATEWAY',
  'ENDLESS PROSPERITY',
  'AFFLUENCE ZONE',
  'RICH FREQUENCY',
  'I AM A WEALTH CREATOR',
  'MILLIONAIRE MINDSET',
  'MONEY FINDS ME',
  'LAW OF ATTRACTION',
  'MONEY MULTIPLIER',
  'FORTUNE FOLLOWS ME',
  'WEALTH PORTAL',
  'PROSPERITY FINDS ME',
  'MONETARY VIBRATION',
  'WEALTH MAGNET',
  'INFINITE CASH',
  'UNLIMITED ABUNDANCE',
  'PROSPERITY MAGNET',
  'MONEY GATEWAY',
  'LIVE IN ABUNDANCE',
  'I DESERVE ABUNDANCE',
  'PROSPERITY FLOW',
  'PROSPERITY PATH',
  'I WILL SUCCEED',
  'DIVINE ABUNDANCE',
  'ABUNDANCE MINDSET',
  'UNLOCK WEALTH',
  'MONEY MAGNET',
  'WEALTH CHANNEL',
  'WEALTH GATEWAY',
  'MONEY FLOWS TO ME',
  'PROSPERITY RADIANCE',
  'FINANCIAL FREEDOM',
  'GOLDEN PROSPERITY',
  'PROSPERITY MINDSET',
  'LUCK FREQUENCY',
  'MY LIFE HAS VALUE',
  'I AM WEALTH',
  'WEALTH MANIFESTATION',
  'FINANCIAL SURPLUS',
  'GOLDEN ENERGY',
  'MONETARY EXPANSION',
  'THE UNIVERSE PROVIDES',
  'GOLDEN VORTEX',
  'I AM RICH',
  'INFINITE PROSPERITY',
  'WEALTH EXPANSION',
  'GOLDEN OPPORTUNITY',
  'INFINITE WEALTH',
  'I DESERVE TO BE RICH',
]
